server:
  port: 8080

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include:
        - '*'

spring:
  jpa:
    show-sql: true
  mvc:
    locale: us
  messages:
    basename: messages
  security:
    user:
      name: user
      password: P@ssword123
  h2:
    console:
      enabled: true
